### ISSUE TITLE
Go 1.5 compatibility (internal/* package visibility)

### ISSUE THREAD

**Issue by vadimsht** [GoogleCloudPlatform/go-endpoints#101]
Attempting to build go-endpoints with 1.5 fails:

=> Fetching dependencies for github.com/GoogleCloudPlatform/go-endpoints/endpoints...
package github.com/GoogleCloudPlatform/go-endpoints/endpoints
	imports google.golang.org/appengine/internal: use of internal package not allowed
package github.com/GoogleCloudPlatform/go-endpoints/endpoints
	imports google.golang.org/appengine/internal/user: use of internal package not allowed

**Comment by danjacques** [comment]
Since the Go AppEngine Managed VM default runtime is now using Go 1.5, code referencing this library now will no longer build with the default runtime. Can we please get this issue resolved?

**Comment by miko-code** [comment]
+1

**Comment by danjacques** [comment]
+2? :+1:

**Comment by vvakame** [comment]
any news? :)
https://groups.google.com/forum/m/#!topic/google-appengine-go/bY_OqNw2Qzo

**Comment by EVILoptimist** [comment]
This is an issue on App Engine Standard as well since the update to 1.6. Application code will compile and run in dev and production environments. However, a `go install` or `goapp install` will fail. Which affects code completion in editors.

**Comment by campoy** [comment]
Thanks for the report and sorry for the delay, working on this now!
