### ISSUE TITLE
Error while go-getting: use of internal package not allowed

### ISSUE THREAD

**Issue by hinoka** [GoogleCloudPlatform/go-endpoints#118]
Go get returns this error:

$ go get github.com/GoogleCloudPlatform/go-endpoints/endpoints
package github.com/GoogleCloudPlatform/go-endpoints/endpoints
        imports google.golang.org/appengine/internal: use of internal package not allowed
package github.com/GoogleCloudPlatform/go-endpoints/endpoints
        imports google.golang.org/appengine/internal/user: use of internal package not allowed

**Comment by bradfitz** [comment]
You're running "go get" from the wrong path. 

But the bug is this package should have that more explicitly declared so you get a good error message.

/cc @okdave @rakyll @gmlewis

**Comment by hinoka** [comment]
Do you mean I'm using the wrong version of go, or my cwd is wrong?

**Comment by bradfitz** [comment]
Francesc, can you handle this? Both answering the question and adding import comments if needed?  (aren't we using cloud.golang.org/... custom import path for these?)

**Comment by campoy** [comment]
The path is correct, but you need to use `goapp get` instead of `go get`

To install `goapp` download the Go SDK for App Engine [here](https://cloud.google.com/appengine/downloads?hl=en)

**Comment by EVILoptimist** [comment]
looks like `goapp` doesn't work either as of the App Engine update to 1.6. Looks like there are a couple issues and PRs out there. #101 #114 #131
