### ISSUE TITLE
JSON Unmarshal not handling IOS client POST

### ISSUE THREAD

**Issue by cadir** [GoogleCloudPlatform/go-endpoints#27]
The Javascript client via API Explorer posts a plain JSON object

  `{"key" : "value", "key2" : value2}`

but the IOS client posts a JSON RPC with the same data wrapped inside a larger object

``` json
{
  "method" : "xxxxx",
  "id" : "gtl_3",
  "jsonrpc" : "2.0",
  "params" : {
    "resource" : {
      "key" : "value", 
      "key2" : value2
    }
  },
  "apiVersion" : "v1"
}
```

In server.go, the request body in the first case works but in the second case cannot be Unmarshal by JSON.

Should go-endpoints be able to handle both cases currently?

**Comment by robskie** [comment]
I think this is related to a known bug in the generated iOS Client [here] (http://stackoverflow.com/q/18149285) which only occurs in the development server.
