### ISSUE TITLE
Support anonymous (embedded) structs

### ISSUE THREAD

**Issue by x1ddos** [GoogleCloudPlatform/go-endpoints#36]
The SPI request body that is generated by Go Endpoints seems to name the anonymously embedded struct, rather than actually embedding the fields of the inner struct in the outer struct, and because of this, JSON unmarshalling of the request struct is not working correctly.

``` go
type Inner struct {
  Name string `json:"name"`
}

type Outer struct {
  Inner
}
```

results in 

``` json
{"Inner": {"name": "..."}}
```

It should result in 

``` json
{"name": "..."}
```

**Comment by riannucci** [comment]
Not sure if this is the same bug, but I'm seeing:

```go
type Embedded struct {
  Something string
}

type SomethingRsp struct {
  *Embedded
}
```

Showing up in the discovery document as

```json
"Embedded": {
  "id": "Embedded",
  "type": "object",
  "properties": {
    "Something": {
      "type": "string"
    }
  }
},

"SomethingRsp": {
  "id": "SomethingRsp",
  "type": "object",
  "properties": {
    "Embedded": {
      "$ref": "Embedded"
    }
  }
}
```

But I would expect it to show up like

```json
"SomethingRsp": {
  "id": "SomethingRsp",
  "type": "object",
  "properties": {
    "Something": {
      "type": "string
    }
  }
}
```

Is this a regression, or the intended behavior?

**Comment by riannucci** [comment]
Ah! I think your fix only works if it's a struct, and not a pointer-to-struct. Pull coming up :)
