### ISSUE TITLE
The User ID (Subject) is not parsed from the JWT Token

### ISSUE THREAD

**Issue by st3fan** [GoogleCloudPlatform/go-endpoints#52]
The JWT token has a `sub` (Subject) field that contains the Google Account ID. This is useful to have in endpoints since it is more stable than the email address.

**Comment by campoy** [comment]
Hey @st3fan, do you have any news on this?
I'll be using this package for a course soon and I would like to make sure after this the API is as stable as possible :smile:

**Comment by st3fan** [comment]
Hi @campoy .. maybe someone else can pick this up? I have abandoned the project that I was initially using this code for so it is difficult for me to pick this up. Maybe @crhym3 has a better idea about what to do here?

**Comment by crhym3** [comment]
Yeah, I'll take it.
