### ISSUE TITLE
Adding the +build appengine tag made the docs disappear

### ISSUE THREAD

**Issue by campoy** [GoogleCloudPlatform/go-endpoints#54]
Not sure if this is a bug for this package or godoc, but seems like a serious issue for developers.

**Comment by maxhawkins** [comment]
Yikes. That's no good.

I suppose we could put the public interface in files without a +build tag and delegate to appengine-specific implementations behind the tag. Do any of the public functions depend on appengine packages?

In the meantime I suppose it makes sense to revert my PR.

**Comment by campoy** [comment]
Unfortunately at least one exported function returns a user.User which means we are bound to appengine and I'm not sure we can analyze appengine depending packages from godoc.

I agree we should revert the PR adding the build tags

**Comment by dhermes** [comment]
For some side context from someone who's dealt with Endpoints and the `user.User` object a lot: You should not feel bad about axing it from the library.

For the long history of annoyance see the [issue][1] and for a description of the quirks, see a StackOverflow [answer][2] from me.

Take this as an opportunity to

1. Make the docs build happily and easily with the build tags you want
1. Drop the unnecessary "problems" discussed in #52 and #53
1. Inform users to stop using the App Engine User ID and start using the Google User ID. (I'd imagine most codebases already have custom user classes, so this inconvenient "convenience" of returning a `user.User` is all around not worth it.)

:grimacing:

[1]: https://code.google.com/p/googleappengine/issues/detail?id=8848
[2]: http://stackoverflow.com/a/16661765/1068170

**Comment by crhym3** [comment]
This is a bug in godoc.org, which @adg will fix.
