### ISSUE TITLE
Travis CI was failed

### ISSUE THREAD

**Issue by vvakame** [GoogleCloudPlatform/go-endpoints#56]
https://travis-ci.org/GoogleCloudPlatform/go-endpoints/builds/46445775
currently master/HEAD is build failed.
https://go-endpoints.appspot.com/

**Comment by crhym3** [comment]
This has been fixed in https://github.com/GoogleCloudPlatform/go-endpoints/commit/bcddc023b1ee19df36bf5e70e584ebc1a945afec
https://travis-ci.org/GoogleCloudPlatform/go-endpoints/builds/47174983
