### ISSUE TITLE
Slices not supported in fields

### ISSUE THREAD

**Issue by campoy** [GoogleCloudPlatform/go-endpoints#57]
Fields of type []string are not supported, adding the field `Strings []string` to [DummyMsg](https://github.com/GoogleCloudPlatform/go-endpoints/blob/master/endpoints/apiconfig_test.go#L68) makes many tests fail with the error:

```
--- FAIL: TestAPIDescriptor (0.00 seconds)
	apiconfig_test.go:135: createDescriptor: error creating descriptor: Unsupported field: &reflect.StructField{Name:"Strings", PkgPath:"", Type:(*reflect.rtype)(0x282a40), Tag:"", Offset:0xa0, Index:[]int{17}, Anonymous:false}
```

**Comment by crhym3** [comment]
Huh.. this is weird. It should be covered in [case fkind == reflect.Slice](https://github.com/GoogleCloudPlatform/go-endpoints/blob/24eb5d4ab4686e08df186593f021bf2d53db40ee/endpoints/apiconfig.go#L299) case.

Let me investigate. I'll report back here.

**Comment by crhym3** [comment]
@campoy I guess we can close this now?

**Comment by campoy** [comment]
Yes, never mind :)
