### ISSUE TITLE
Memcache for cert

### ISSUE THREAD

**Issue by sabrinatseng** [GoogleCloudPlatform/go-endpoints#62]
https://github.com/GoogleCloudPlatform/go-endpoints/blob/master/endpoints/auth.go#L191
namespacedContext, err := appengine.Namespace(c, certNamespace)	
// The certNamespace is static "__verify_jwt"

https://github.com/GoogleCloudPlatform/go-endpoints/blob/master/endpoints/auth.go#L198
_, err = memcache.JSON.Get(namespacedContext, DefaultCertURI, &certs)
The DefaultCertURI is static "https://www.googleapis.com/service_accounts/v1/metadata/raw/federated-signon@system.gserviceaccount.com"

**Different user will save and get their cert in the same memcache.**

Please let me know if I am wrong. Thanks in advance.

**Comment by crhym3** [comment]
What do you mean? I think you are wrong.

**Comment by dhermes** [comment]
That CERT is for checking **all** the ID tokens, which have their 3rd part (the signature in a JWT) signed by it.

**Comment by sabrinatseng** [comment]
Hi Danny,

Thank you for your clarification. Sorry my bad, CERT == certificate.


2015-03-01 2:59 GMT+08:00 Danny Hermes <notifications@github.com>:
