### ISSUE TITLE
slices still not supported in fields

### ISSUE THREAD

**Issue by robert-king** [GoogleCloudPlatform/go-endpoints#64]
related: https://github.com/GoogleCloudPlatform/go-endpoints/issues/57

I haven't managed to get slices working in the request (got them working in the response).

For the github example you provide. I got the `List()` method working for the greeting service. This returns a GreetingsList method which contains a list of greetings.

However, I was unable to get the `GreetingsList` to be the request, see my modified function:

```go
func (gs *GreetingService) List(c endpoints.Context, r *GreetingsList) (*GreetingsList, error) {
    return r, nil
}
```

In the function above we get:

```
2015/03/05 02:29:01 ERROR: Unsupported field: &reflect.StructField{Name:"Items", PkgPath:"", Type:(*reflect.rtype)(0x2c4a80), Tag:"json:\"items\"", Offset:0x0, Index:[]int{0}, Anonymous:false}
```

greetings and greetings list are as follows:

```go
// Greeting is a datastore entity that represents a single greeting.
// It also serves as (a part of) a response of GreetingService.
type Greeting struct {
  Key     *datastore.Key `json:"id" datastore:"-"`
  Author  string         `json:"author"`
  Content string         `json:"content" datastore:",noindex" endpoints:"req"`
  Date    time.Time      `json:"date"`
}

// GreetingsList is a response type of GreetingService.List method
type GreetingsList struct {
  Items []*Greeting `json:"items"`
}
```

For me I'm wanting to use a list of strings in my request. e.g. Strings []string.

Is there something wrong i'm doing - or is this a bug?

thanks

**Comment by crhym3** [comment]
Actually, I think it's working as intended :tm: 

If your `List()` method corresponds to a `GET` request, how would you stuff a slice of items into the URL query params? Endpoints don't do that kind of conversion.

I believe this will only work if you make the `List()` to be a `POST` or a `PUT`.

**Comment by robert-king** [comment]
Ta - Changed GET to POST and it works.

Potential suggestions:
1. Improve Error message to suggest using POST instead of GET for slices (not sure if possible with go)
2. Note in the documentation that slices can't be used with GET
3. Potentially make it slices work with GET?
4. Do nothing - people will google search Unsupported Field and find this page :)

This can now be closed - thanks!
