### ISSUE TITLE
Generate signed URL 

### ISSUE THREAD

**Issue by miko-code** [GoogleCloudPlatform/go-endpoints#66]
Hey ,
I thinking to create a   signed url func  that will return  the URL to  the  client  and he will upload and download the files directly from Cloud storage.
I used those  link as reference 
1.https://cloud.google.com/storage/docs/access-control#signing-code-go
2.https://github.com/GoogleCloudPlatform/gcloud-golang/blob/master/storage/storage.go
I'm looking to use the  *&storage.SignedURLOptions* method
My only issue is how can i generate the private  key   on the cloud endpoints framework 
Can i save the pem file somewhere ?

**Comment by crhym3** [comment]
GAE apps can read files from disk. I don't see why you wouldn't be able to read a key.
This is not a go-endpoints issue. [StackOverflow](http://stackoverflow.com/questions/tagged/google-app-engine) is far better fit for such questions.
