### ISSUE TITLE
Returning  custom HTTP code 

### ISSUE THREAD

**Issue by miko-code** [GoogleCloudPlatform/go-endpoints#73]
Hey ,

I want to return  a HTTP custom  code    ,now for each success request im getting  HTTP 200 
I cant figure out were  the http.StatusOK is set?
What will be the  correct way to implement it without breaking something...

**Comment by campoy** [comment]
You could do this:
```go
func doSomething(c endpoints.Context) error {
    return endpoints.NewAPIError("Accepted", "everything worked", http.StatusCreated) 
}
```
More docs here: http://godoc.org/github.com/GoogleCloudPlatform/go-endpoints/endpoints#NewAPIError

**Comment by miko-code** [comment]
That nice , 
There   is a way to return my own struct and  the error response struct ?

**Comment by campoy** [comment]
Yes ,see http://godoc.org/github.com/GoogleCloudPlatform/go-endpoints/endpoints#APIError
