### ISSUE TITLE
The regexp curlyBrackets used for Duplicate method detection is greedy matching

### ISSUE THREAD

**Issue by jonprice** [GoogleCloudPlatform/go-endpoints#74]
In the APIDescriptor function in apiconfig.go there is checking for duplicate methods. 

If you have the following 

/object1/{id}

and 

/object1/{id}/object2{id2}

the both get matched as the same thing because the curlyBrackets regex is greedy matching /object1/{id}/object2{id2} to /object1/{} instead of /object1/{}/object2{}  i.e.   .+ is matching to the text id}/object2{id2

**Comment by jonprice** [comment]
Added pull request with fix and test https://github.com/GoogleCloudPlatform/go-endpoints/pull/75

**Comment by campoy** [comment]
👍
