### ISSUE TITLE
Support for managed VMs

### ISSUE THREAD

**Issue by robskie** [GoogleCloudPlatform/go-endpoints#76]
Hi!

I'm currently using a ported version (I just changed appengine.Context to context.Context and logging codes such as c.Debugf(...) to google.golang.org/appengine/log methods) so that I can use endpoints on managed VMs, but it would be great if managed VMs can be officially supported. Is there any time frame on when it would be supported?

**Comment by albertog** [comment]
+1

**Comment by campoy** [comment]
PR https://github.com/GoogleCloudPlatform/go-endpoints/pull/81 is working on fixing this.
