### ISSUE TITLE
json tags validation 

### ISSUE THREAD

**Issue by miko-code** [GoogleCloudPlatform/go-endpoints#79]
Hi , 
In the struct usage example  , you use the  **endpoints:"req"`**
 that suppose to be  a mandatory field ?
I tried to pass an empty value to a  field with the endpoints:req  tag and i didn't get any error
What will be the best way to valid mandatory fields ? 

i can do something like that but it must be a nicer solution

```
if len(subscriptionToken) == 0 {
		return endpoints.NewAPIError("subscriptionToken is empty", "subscriptionToken is empty", 400)
	}
```

**Comment by campoy** [comment]
First attempt to fix this: https://github.com/GoogleCloudPlatform/go-endpoints/pull/87/files

**Comment by campoy** [comment]
dup of #72
