### ISSUE TITLE
api method taking struct from wrong package

### ISSUE THREAD

**Issue by robert-king** [GoogleCloudPlatform/go-endpoints#80]
I have this code which works perfectly:

    package api
    import (
    	"github.com/GoogleCloudPlatform/go-endpoints/endpoints"
    	"github.com/robert-king/studentcoursereview/backends/gopackages/course"
    	"log"
    )
    type Course2 struct {
        DomainName string `json:"domainName" endpoints:"req,desc=name of domain or university"`
        CourseGroup string `json:"courseGroup" endpoints:"req,desc=name of course group e.g. biosci"`
        CourseName string `json:"courseName" endpoints:"req,desc=name of course e.g. biosci101"`
        CourseTitle string `json:"courseTitle" endpoints:"req,desc=course title or empty string"`
    }

    func (sa *ScrApi) CreateCourse(c endpoints.Context, course_ *Course2) (error) {
        return course.CreateCourse(c,course_.DomainName, course_.CourseGroup, course_.CourseName, course_.CourseTitle)
    }

    ...

    register("CreateCourse", "createCourse", "POST", "createCourse", "createCourse")

I have another package called course. Inside course I have a different struct called Course.
If I rename "Course2" to be "Course". Then in the api explorer & client will for some reason expect the Course struct from the course package rather than the Course struct from the api package which breaks everything. Furthermore renaming "Course" to "Course3" in the course package, and renaming "Course2" to Course" in the api package fixed things - so basically the struct name in a different package can break the api.
Cheers.

**Comment by campoy** [comment]
Hi,

What is `register` exactly? if you use `RegisterService` it should work because you pass a value of whatever type you want to register, rather than by using name.

I guess this is obsolete? Sorry for taking so long to reply.
